# Helper functions to query database
# Per-session dataset manager for a user points table in Postgres

library(DBI)
library(pool)
library(uuid)
library(shiny)

# ---- helper: run code with a checked-out pool connection ----
with_pool_connection <- function(pool, fun) {
  conn <- pool::poolCheckout(pool)
  on.exit(pool::poolReturn(conn), add = TRUE)
  fun(conn)
}

# ---- base empty table ----
create_empty_points_table <- function(conn, table_id) {
  tbl_q <- DBI::dbQuoteIdentifier(conn, table_id)
  DBI::dbExecute(conn, paste0(
    "CREATE TABLE ", tbl_q, " (
       id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       latitude double precision,
       longitude double precision
     )"
  ))
}


# ---- ensure extra columns exist  ----
ensure_points_schema <- function(conn, table_id) {
  tbl_q <- DBI::dbQuoteIdentifier(conn, table_id)

  DBI::dbExecute(conn, paste0(
    "ALTER TABLE ", tbl_q, "
      ADD COLUMN IF NOT EXISTS geom_orig geometry(POINT,4326),
      ADD COLUMN IF NOT EXISTS geom_hint geometry(POINT,4326),
      ADD COLUMN IF NOT EXISTS geom_snap geometry(POINT,4326),
      ADD COLUMN IF NOT EXISTS snap_state text DEFAULT 'needs_snap',
      ADD COLUMN IF NOT EXISTS snap_fail_reason text,

      ADD COLUMN IF NOT EXISTS subc_id integer,
      ADD COLUMN IF NOT EXISTS basin_id integer,
      ADD COLUMN IF NOT EXISTS strahler_order smallint,
      ADD COLUMN IF NOT EXISTS reg_id smallint,
      ADD COLUMN IF NOT EXISTS hylak_id integer,
      ADD COLUMN IF NOT EXISTS upstream bigint[],

      -- caching / staleness detection for upstream computation
      ADD COLUMN IF NOT EXISTS upstream_key text,
      ADD COLUMN IF NOT EXISTS upstream_calc_at timestamptz"
  ))

  invisible(TRUE)
}



# ---- read points from DB for editor/map/table (lat/lon + optional snap) ----
read_points_db <- function(conn, table_id) {
  tbl_q <- DBI::dbQuoteIdentifier(conn, table_id)

  DBI::dbGetQuery(conn, paste0(
    "SELECT
       id,
       latitude,
       longitude,
       snap_state,
       CASE
         WHEN COALESCE(geom_snap, geom_hint) IS NULL THEN NULL
         ELSE round(ST_Y(COALESCE(geom_snap, geom_hint))::numeric, 6)
       END AS latitude_snap,
       CASE
         WHEN COALESCE(geom_snap, geom_hint) IS NULL THEN NULL
         ELSE round(ST_X(COALESCE(geom_snap, geom_hint))::numeric, 6)
       END AS longitude_snap
     FROM ", tbl_q, "
     ORDER BY id"
  ))
}



# Write points into DB
write_points_base_db <- function(conn, table_id, df_base) {
  ensure_points_schema(conn, table_id)
  tbl_q <- DBI::dbQuoteIdentifier(conn, table_id)

  # ---- Validate/coerce id safely (BIGINT-friendly) ----
  id_num <- suppressWarnings(as.numeric(df_base$id))

  if (anyNA(id_num)) {
    bad <- which(is.na(id_num))
    stop("Invalid id(s): cannot coerce to numeric. Bad row(s): ", paste(head(bad, 20), collapse = ", "))
  }
  if (any(!is.finite(id_num))) {
    bad <- which(!is.finite(id_num))
    stop("Invalid id(s): not finite. Bad row(s): ", paste(head(bad, 20), collapse = ", "))
  }
  if (any(id_num %% 1 != 0)) {
    bad <- which(id_num %% 1 != 0)
    stop("Invalid id(s): must be whole numbers. Bad row(s): ", paste(head(bad, 20), collapse = ", "))
  }

  # keep as numeric in R; Postgres BIGINT will store it
  df_base$id <- id_num

  # ---- Reset table ----
  DBI::dbExecute(conn, paste0("TRUNCATE TABLE ", tbl_q, " RESTART IDENTITY"))

  # ---- Write ----
  DBI::dbWriteTable(conn, table_id, df_base, append = TRUE, row.names = FALSE)

  # ---- Recompute derived fields ----
  DBI::dbExecute(conn, paste0(
    "UPDATE ", tbl_q, "
     SET geom_orig = ST_SetSRID(ST_MakePoint(longitude, latitude), 4326),
         geom_hint = NULL,
         geom_snap = NULL,
         snap_state = 'needs_snap',
         snap_fail_reason = NULL"
  ))

  DBI::dbExecute(conn, paste0("ANALYZE ", tbl_q))
  invisible(TRUE)
}


# ---- dataset manager ----
dataset_manager <- function(pool, session, schema = "shiny_user", prefix = "points_") {

  # ---- internal state stored in session$userData ----
  if (is.null(session$userData$points_table_name)) session$userData$points_table_name <- NULL
  if (is.null(session$userData$points_version))    session$userData$points_version    <- 0L

  # NEW: reactive trigger (this is what Shiny can depend on)
  if (is.null(session$userData$points_version_rv)) {
    session$userData$points_version_rv <- shiny::reactiveVal(0L)
  }

  ensure <- function() {
    tn <- session$userData$points_table_name
    if (!is.null(tn)) return(tn)

    uuid_str   <- uuid::UUIDgenerate(use.time = TRUE)
    table_name <- paste0(prefix, uuid_str)
    table_id   <- DBI::Id(schema = schema, table = table_name)

    with_pool_connection(pool, function(conn) {
      create_empty_points_table(conn, table_id)
      ensure_points_schema(conn, table_id)
    })

    session$userData$points_table_name <- table_name

    session$onSessionEnded(function() {
      with_pool_connection(pool, function(conn) {
        DBI::dbRemoveTable(conn, table_id, fail_if_missing = FALSE)
      })
    })

    table_name
  }

  get_table_name <- function() ensure()
  get_table_id   <- function() DBI::Id(schema = schema, table = ensure())

  # ---- versioning: invalidate reactive readers after DB writes ----
  bump_version <- function() {
    # keep your plain integer counter (optional, but fine)
    session$userData$points_version <- as.integer(session$userData$points_version) + 1L

    # THIS is the reactive invalidation trigger
    v <- session$userData$points_version_rv()
    session$userData$points_version_rv(v + 1L)

    invisible(session$userData$points_version)
  }

  # reactive dependency (use inside reactive({ ... }))
  version <- function() {
    session$userData$points_version_rv()
  }

  table_name_reactive <- shiny::reactive({ ensure() })

  read_points <- function() {
    ensure()
    with_pool_connection(pool, function(conn) {
      read_points_db(conn, get_table_id())
    })
  }

  list(
    ensure         = ensure,
    get_table_name = get_table_name,
    table_name     = table_name_reactive,
    table_id       = get_table_id,
    bump_version   = bump_version,
    version        = version,
    read_points    = read_points
  )
}

# Save “original edits” (workflows 3 & 4)
# TRUNCATE+insert base points (handles add/delete),
# recompute geom_orig, and reset snapping.

save_original_edits_db <- function(conn, table_id, df_base) {
  ensure_points_schema(conn, table_id)
  tbl_q <- DBI::dbQuoteIdentifier(conn, table_id)

  df_base <- df_base[, c("id", "latitude", "longitude"), drop = FALSE]

  # ---- Validate/coerce id safely (BIGINT-friendly) ----
  id_num <- suppressWarnings(as.numeric(df_base$id))

  if (anyNA(id_num)) {
    bad <- which(is.na(id_num))
    stop("Invalid id(s): cannot coerce to numeric. Bad row(s): ",
         paste(head(bad, 20), collapse = ", "))
  }
  if (any(!is.finite(id_num))) {
    bad <- which(!is.finite(id_num))
    stop("Invalid id(s): not finite. Bad row(s): ",
         paste(head(bad, 20), collapse = ", "))
  }
  if (any(id_num %% 1 != 0)) {
    bad <- which(id_num %% 1 != 0)
    stop("Invalid id(s): must be whole numbers. Bad row(s): ",
         paste(head(bad, 20), collapse = ", "))
  }

  # Optional but helpful: detect duplicates early (otherwise PK violation later)
  if (any(duplicated(id_num))) {
    dup <- unique(id_num[duplicated(id_num)])
    stop("Invalid id(s): duplicated id(s): ", paste(head(dup, 20), collapse = ", "))
  }

  df_base$id <- id_num

  # ---- Wipe + write ----
  DBI::dbExecute(conn, paste0("TRUNCATE TABLE ", tbl_q, " RESTART IDENTITY"))
  DBI::dbWriteTable(conn, table_id, df_base, append = TRUE, row.names = FALSE)

  # ---- Recompute + reset derived fields ----
  DBI::dbExecute(conn, paste0(
    "UPDATE ", tbl_q, "
        SET geom_orig = ST_SetSRID(ST_MakePoint(longitude, latitude), 4326),
            geom_hint = NULL,
            geom_snap = NULL,
            snap_state = 'needs_snap',
            snap_fail_reason = NULL,
            subc_id = NULL,
            basin_id = NULL,
            strahler_order = NULL,
            reg_id = NULL,
            hylak_id = NULL,
            upstream = NULL"
  ))

  DBI::dbExecute(conn, paste0("ANALYZE ", tbl_q))
  invisible(TRUE)
}



# Save “manual snapped edits” (workflow 2).
# Update geom_hint only for changed snapped marker positions, and set
# snap_state='needs_snap' (but keep original points unchanged).

save_snap_hints_db <- function(conn, table_id, df_hint) {
  ensure_points_schema(conn, table_id)
  tbl_q <- DBI::dbQuoteIdentifier(conn, table_id)

  df_hint <- df_hint[, c("id", "latitude_snap", "longitude_snap"), drop = FALSE]

  # ---- Validate/coerce id safely (BIGINT-friendly) ----
  id_num <- suppressWarnings(as.numeric(df_hint$id))
  if (anyNA(id_num)) {
    bad <- which(is.na(id_num))
    stop("Invalid id(s): cannot coerce to numeric. Bad row(s): ", paste(head(bad, 20), collapse = ", "))
  }
  if (any(!is.finite(id_num))) {
    bad <- which(!is.finite(id_num))
    stop("Invalid id(s): not finite. Bad row(s): ", paste(head(bad, 20), collapse = ", "))
  }
  if (any(id_num %% 1 != 0)) {
    bad <- which(id_num %% 1 != 0)
    stop("Invalid id(s): must be whole numbers. Bad row(s): ", paste(head(bad, 20), collapse = ", "))
  }

  # Use character ids for interpolation, and cast to bigint in SQL for exact matching
  df_hint$id_chr <- format(id_num, scientific = FALSE, trim = TRUE)

  for (i in seq_len(nrow(df_hint))) {
    idv <- df_hint$id_chr[i]
    lat <- df_hint$latitude_snap[i]
    lon <- df_hint$longitude_snap[i]
    if (!is.finite(lat) || !is.finite(lon)) next

    DBI::dbExecute(conn, DBI::sqlInterpolate(
      conn,
      paste0(
        "UPDATE ", tbl_q, "
        SET geom_hint = ST_SetSRID(ST_MakePoint(?lon, ?lat), 4326),
            geom_snap = NULL,
            snap_state = 'needs_snap',
            snap_fail_reason = NULL,
            subc_id = NULL,
            basin_id = NULL,
            strahler_order = NULL,
            reg_id = NULL,
            hylak_id = NULL,
            upstream = NULL
      WHERE id = (?id)::bigint"
      ),
      id = idv, lat = lat, lon = lon
    ))

  }

  DBI::dbExecute(conn, paste0("ANALYZE ", tbl_q))
  invisible(TRUE)
}



# ---- DB helper: snap points to stream in their subcatchment (shared) ----
# conn: a real DBI connection (NOT the pool)
# points_table: DBI::Id(schema="shiny_user", table="points_<uuid>")
# progress: optional function(pct) to report progress (0..100)
# Returns: invisible(TRUE). Updates DB table in-place.
snap_points_subcatchment_db <- function(conn, points_table, progress = NULL) {

  progress <- progress %||% function(...) invisible(NULL)

  # Ensure schema exists (now includes geom_* AND derived columns)
  ensure_points_schema(conn, points_table)

  pt_q <- DBI::dbQuoteIdentifier(conn, points_table)

  # Build a clean base name for the spatial index (63-char limit)
  idx_base <- if (inherits(points_table, "Id")) {
    nm <- points_table@name
    if (!is.null(names(nm)) && "table" %in% names(nm)) nm[["table"]] else tail(nm, 1)
  } else {
    as.character(points_table)
  }

  # 1) Build geom_orig with SRID 4326
  DBI::dbExecute(conn, paste0(
    "UPDATE ", pt_q, "
       SET geom_orig = ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)"
  ))
  progress(25)

  # 2) Spatial index on geom_orig (idempotent; create only once)
  idx_name <- substr(paste0(idx_base, "_geom_orig_idx"), 1, 63)
  idx_q <- DBI::dbQuoteIdentifier(conn, idx_name)

  DBI::dbExecute(conn, paste0(
    "CREATE INDEX IF NOT EXISTS ", idx_q,
    " ON ", pt_q, " USING GIST (geom_orig)"
  ))
  progress(40)

  # 3) reg_id  (CHANGED: hint can move points across regions)
  reg_q <- DBI::dbQuoteIdentifier(conn, DBI::Id(schema = "hydro", table = "regional_units"))
  DBI::dbExecute(conn, paste0(
    "UPDATE ", pt_q, " poi
        SET reg_id = reg.reg_id
       FROM ", reg_q, " reg
      WHERE ST_Intersects(COALESCE(poi.geom_hint, poi.geom_orig), reg.geom)"
  ))
  progress(60)

  # 4) hylak_id (CHANGED: hint can move points into/out of lakes)
  lak_q <- DBI::dbQuoteIdentifier(conn, DBI::Id(schema = "hydro", table = "hydrolakes_poly"))
  DBI::dbExecute(conn, paste0(
    "UPDATE ", pt_q, " poi
        SET hylak_id = lak.hylak_id
       FROM ", lak_q, " lak
      WHERE ST_Intersects(COALESCE(poi.geom_hint, poi.geom_orig), lak.geom)"
  ))
  progress(72)

  # 5) subc_id + basin_id (CHANGED: subcatchment follows the hint when present)
  subc_q <- DBI::dbQuoteIdentifier(conn, DBI::Id(schema = "hydro", table = "sub_catchments"))
  DBI::dbExecute(conn, paste0(
    "UPDATE ", pt_q, " poi SET
           subc_id  = sub.subc_id,
           basin_id = sub.basin_id
      FROM ", subc_q, " sub
     WHERE ST_Intersects(COALESCE(poi.geom_hint, poi.geom_orig), sub.geom)
       AND poi.reg_id = sub.reg_id"
  ))
  progress(85)

  # 6) Snap to segment within (new) subcatchment
  seg_q <- DBI::dbQuoteIdentifier(conn, DBI::Id(schema = "hydro", table = "stream_segments"))
  DBI::dbExecute(conn, paste0(
    "UPDATE ", pt_q, " poi SET
         strahler_order = seg.strahler,
         geom_snap = ST_LineInterpolatePoint(
           seg.geom,
           ST_LineLocatePoint(seg.geom, COALESCE(poi.geom_hint, poi.geom_orig))
         ),
         snap_state = 'snapped',
         snap_fail_reason = NULL
    FROM ", seg_q, " seg
    WHERE seg.subc_id = poi.subc_id"
  ))

  # Mark failures (no snapped geometry produced)
  DBI::dbExecute(conn, paste0(
    "UPDATE ", pt_q, "
        SET snap_state = 'failed',
            snap_fail_reason = 'no segment in subcatchment'
      WHERE geom_snap IS NULL"
  ))
  progress(95)

  DBI::dbExecute(conn, paste0("ANALYZE ", pt_q))
  progress(100)

  invisible(TRUE)
}


snap_points_strahler_db <- function(
    conn,
    points_table,
    target_strahler,
    search_radius_m = 500,
    progress = NULL
) {
  progress <- progress %||% function(...) invisible(NULL)

  ensure_points_schema(conn, points_table)
  pt_q <- DBI::dbQuoteIdentifier(conn, points_table)

  seg_q  <- DBI::dbQuoteIdentifier(conn, DBI::Id(schema = "hydro", table = "stream_segments"))
  subc_q <- DBI::dbQuoteIdentifier(conn, DBI::Id(schema = "hydro", table = "sub_catchments"))

  # 1) refresh geom_orig
  DBI::dbExecute(conn, paste0(
    "UPDATE ", pt_q, "
       SET geom_orig = ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)"
  ))
  progress(20)

  # 2) snap to nearest segment with given Strahler order within radius (meters)
  # Use LATERAL to pick exactly ONE best segment per point.
  DBI::dbExecute(conn, paste0(
    "WITH snapped AS (
       SELECT
         poi.id,
         seg.subc_id AS new_subc_id,
         seg.strahler AS new_strahler,
         ST_LineInterpolatePoint(
           seg.geom,
           ST_LineLocatePoint(seg.geom, pt.ptgeom)
         ) AS new_geom_snap
       FROM ", pt_q, " poi
       CROSS JOIN LATERAL (
         SELECT COALESCE(poi.geom_hint, poi.geom_orig) AS ptgeom
       ) pt
       LEFT JOIN LATERAL (
         SELECT s.*
         FROM ", seg_q, " s
         WHERE s.strahler = ", as.integer(target_strahler), "
           AND ST_DWithin(s.geom::geography, pt.ptgeom::geography, ", as.numeric(search_radius_m), ")
         ORDER BY ST_Distance(s.geom::geography, pt.ptgeom::geography)
         LIMIT 1
       ) seg ON TRUE
     )
     UPDATE ", pt_q, " p
        SET geom_snap = s.new_geom_snap,
            subc_id   = s.new_subc_id,
            strahler_order = s.new_strahler,
            snap_state = CASE WHEN s.new_geom_snap IS NULL THEN 'failed' ELSE 'snapped' END,
            snap_fail_reason = CASE WHEN s.new_geom_snap IS NULL THEN 'no stream segment found (strahler filter / radius)' ELSE NULL END
       FROM snapped s
      WHERE p.id = s.id"
  ))
  progress(75)

  # 3) update basin_id from new subc_id (where available)
  DBI::dbExecute(conn, paste0(
    "UPDATE ", pt_q, " p
        SET basin_id = sub.basin_id
       FROM ", subc_q, " sub
      WHERE p.subc_id = sub.subc_id"
  ))
  progress(90)

  DBI::dbExecute(conn, paste0("ANALYZE ", pt_q))
  progress(100)

  invisible(TRUE)
}


# Read lakes for points
read_lakes_for_points_db <- function(conn, points_table) {
  pt_q <- DBI::dbQuoteIdentifier(conn, points_table)
  hl_q <- DBI::dbQuoteIdentifier(conn, DBI::Id(schema = "hydro", table = "hydrolakes_poly"))
  li_q <- DBI::dbQuoteIdentifier(conn, DBI::Id(schema = "hydro", table = "lake_intersections"))

  DBI::dbGetQuery(conn, paste0(
    "SELECT poi.id, poi.hylak_id,
            hylak.lake_name AS hydrolake_name, hylak.lake_area AS hydrolake_area,
            lak.subc_id AS outlet_subc_id,
            round(lak.latitude::numeric, 6) AS outlet_latitude,
            round(lak.longitude::numeric, 6) AS outlet_longitude
       FROM ", pt_q, " poi
       JOIN ", hl_q, " hylak
         ON poi.hylak_id = hylak.hylak_id
       JOIN ", li_q, " lak
         ON poi.hylak_id = lak.hylak_id
        AND poi.reg_id = lak.reg_id
      WHERE lak.outlet_id = 1"
  ))
}

# Use this function to update the point table in the database when all points are
# deleted in the point editor
wipe_points_db <- function(conn, table_id) {
  ensure_points_schema(conn, table_id)
  tbl_q <- DBI::dbQuoteIdentifier(conn, table_id)

  # delete all rows (and reset identity if you rely on it)
  DBI::dbExecute(conn, paste0("TRUNCATE TABLE ", tbl_q, " RESTART IDENTITY"))

  DBI::dbExecute(conn, paste0("ANALYZE ", tbl_q))
  invisible(TRUE)
}
