# ==== Climate (CHELSA bioclimatic variables) ====
Climate_choices <- c(
  "Annual mean temperature (bio1)"                      = "bio1",
  "Mean diurnal range (bio2)"                           = "bio2",
  "Isothermality (bio3)"                                = "bio3",
  "Temperature seasonality (bio4)"                      = "bio4",
  "Max temperature of warmest month (bio5)"             = "bio5",
  "Min temperature of coldest month (bio6)"             = "bio6",
  "Temperature annual range (bio7)"                     = "bio7",
  "Mean temperature of wettest quarter (bio8)"          = "bio8",
  "Mean temperature of driest quarter (bio9)"           = "bio9",
  "Mean temperature of warmest quarter (bio10)"         = "bio10",
  "Mean temperature of coldest quarter (bio11)"         = "bio11",
  "Annual precipitation (bio12)"                        = "bio12",
  "Precipitation of wettest month (bio13)"              = "bio13",
  "Precipitation of driest month (bio14)"               = "bio14",
  "Precipitation seasonality (bio15)"                   = "bio15",
  "Precipitation of wettest quarter (bio16)"            = "bio16",
  "Precipitation of driest quarter (bio17)"             = "bio17",
  "Precipitation of warmest quarter (bio18)"            = "bio18",
  "Precipitation of coldest quarter (bio19)"            = "bio19"
)

Climate_desc <- c(
  bio1  = "Annual Mean Temperature (°C).",
  bio2  = "Mean Diurnal Range (°C) – mean monthly (Tmax − Tmin).",
  bio3  = "Isothermality (×100, dimensionless).",
  bio4  = "Temperature Seasonality (SD ×100, dimensionless).",
  bio5  = "Max Temperature of Warmest Month (°C).",
  bio6  = "Min Temperature of Coldest Month (°C).",
  bio7  = "Annual Temperature Range (°C).",
  bio8  = "Mean Temperature of Wettest Quarter (°C).",
  bio9  = "Mean Temperature of Driest Quarter (°C).",
  bio10 = "Mean Temperature of Warmest Quarter (°C).",
  bio11 = "Mean Temperature of Coldest Quarter (°C).",
  bio12 = "Annual Precipitation (kg/m²).",
  bio13 = "Precipitation of Wettest Month (kg/m²).",
  bio14 = "Precipitation of Driest Month (kg/m²).",
  bio15 = "Precipitation Seasonality (% CV).",
  bio16 = "Precipitation of Wettest Quarter (kg/m²).",
  bio17 = "Precipitation of Driest Quarter (kg/m²).",
  bio18 = "Precipitation of Warmest Quarter (kg/m²).",
  bio19 = "Precipitation of Coldest Quarter (kg/m²)."
)

# ==== Soil (SoilGrids250m) ====
Soil_choices <- c(
  "Derived saturated water content (awcts)"          = "awcts",
  "Clay content (clyppt)"                            = "clyppt",
  "Sand content (sndppt)"                            = "sndppt",
  "Silt content (sltppt)"                            = "sltppt",
  "Derived available soil water capacity (wwp)"      = "wwp",
  "Soil organic carbon content (orcdrc)"             = "orcdrc",
  "Soil pH ×10 in H₂O (phihox)"                      = "phihox",
  "Bulk density (bldfie)"                            = "bldfie",
  "Cation exchange capacity (cecsol)"                = "cecsol",
  "Coarse fragments volumetric (crfvol)"             = "crfvol",
  "Grade of a sub-soil being acid (acdwrb)"          = "acdwrb",
  "Depth to bedrock (R horizon) (bdricm)"            = "bdricm",
  "Probability of occurrence of R horizon (bdrlog)"  = "bdrlog",
  "Cumulative probability of organic soil (histpr)"  = "histpr",
  "Sodic soil grade (slgwrb)"                        = "slgwrb"
)

Soil_desc <- c(
  awcts   = "Derived saturated water content (cm³/cm³).",
  clyppt  = "Clay content (% weight).",
  sndppt  = "Sand content (% weight).",
  sltppt  = "Silt content (% weight).",
  wwp     = "Available soil water capacity (cm³/cm³).",
  orcdrc  = "Soil organic carbon content (g/kg).",
  phihox  = "Soil pH in H₂O ×10 (pH ×10).",
  bldfie  = "Bulk density (kg/m³).",
  cecsol  = "Cation exchange capacity (cmol(c)/kg).",
  crfvol  = "Coarse fragments volumetric fraction (% volume).",
  acdwrb  = "Grade of a sub-soil being acid (WRB index).",
  bdricm  = "Depth to bedrock (cm).",
  bdrlog  = "Probability of R horizon (0–1).",
  histpr  = "Probability of organic soil (0–1).",
  slgwrb  = "Sodic soil grade (WRB index)."
)

# ==== Topography (Hydrography90m) ====
Topography_choices <- c(
  "Mean elevation (elev)"                              = "elev",
  "Flow accumulation (flowpos)"                        = "flowpos",
  "Cell maximum curvature"                             = "cell_max_curv",
  "Cell minimum curvature"                             = "cell_min_curv",
  "Cell elevation difference"                          = "cell_elev_diff",
  "Cell gradient"                                      = "cell_gradient",
  "Shortest distance to drainage divide"               = "shortest_dist_divide",
  "Longest distance to drainage divide"                = "longest_dist_divide",
  "Nearest downstream stream grid cell"                = "nearest_downstream_stream_cell",
  "Outlet grid cell in the network"                    = "outlet_cell_network",
  "Downstream stream node grid cell"                   = "downstream_stream_node_cell",
  "Euclidean distance"                                 = "euclid_dist",
  "Shortest path"                                      = "shortest_path",
  "Longest path"                                       = "longest_path",
  "Nearest downstream stream pixel"                    = "nearest_downstream_stream_pixel",
  "Segment downstream mean gradient"                   = "seg_down_mean_grad",
  "Segment upstream mean gradient"                     = "seg_up_mean_grad",
  "Cell upstream gradient"                             = "cell_upstream_grad",
  "Cell stream course curvature"                       = "cell_stream_course_curv",
  "Segment downstream elevation difference"            = "seg_down_elev_diff",
  "Segment upstream elevation difference"              = "seg_up_elev_diff",
  "Cell upstream elevation difference"                 = "cell_upstream_elev_diff",
  "Cell downstream elevation difference"               = "cell_downstream_elev_diff",
  "Segment downstream distance"                        = "seg_down_dist",
  "Segment upstream distance"                          = "seg_up_dist",
  "Cell upstream distance"                             = "cell_upstream_dist",
  "Strahler’s stream order (stream_strahler)"          = "stream_strahler",
  "Shreve’s stream magnitude (stream_shreve)"          = "stream_shreve",
  "Horton’s stream order (stream_horton)"              = "stream_horton",
  "Hack’s stream order (stream_hack)"                  = "stream_hack",
  "Topological dimension of streams"                   = "topo_dim_streams",
  "Length of the stream reach (length)"                = "length",
  "Straight length (stright)"                          = "stright",
  "Sinusoid of the stream reach (sinusoid)"            = "sinusoid",
  "Accumulated length (cum_length)"                    = "cum_length",
  "Distance to outlet (out_dist)"                      = "out_dist",
  "Source elevation (source_elev)"                     = "source_elev",
  "Outlet elevation (outlet_elev)"                     = "outlet_elev",
  "Elevation drop (elev_drop)"                         = "elev_drop",
  "Outlet drop (out_drop)"                             = "out_drop",
  "Gradient (gradient)"                                = "gradient",
  "Stream power index (spi)"                           = "spi",
  "Sediment transportation index (sti)"                = "sti",
  "Compound topographic index (cti)"                   = "cti"
)

Topography_desc <- c(
  elev                        = "Mean elevation (m).",
  flowpos                     = "Flow accumulation (number of upstream cells, dimensionless).",
  cell_max_curv               = "Cell maximum curvature (dimensionless).",
  cell_min_curv               = "Cell minimum curvature (dimensionless).",
  cell_elev_diff              = "Cell elevation difference (m).",
  cell_gradient               = "Cell gradient (m/m, dimensionless slope).",
  shortest_dist_divide        = "Shortest distance to drainage divide (m).",
  longest_dist_divide         = "Longest distance to drainage divide (m).",
  nearest_downstream_stream_cell = "Nearest downstream stream grid cell (index, dimensionless).",
  outlet_cell_network         = "Outlet grid cell in the network (index, dimensionless).",
  downstream_stream_node_cell = "Downstream stream node grid cell (index, dimensionless).",
  euclid_dist                 = "Euclidean distance (m).",
  shortest_path               = "Shortest path along flow direction (m).",
  longest_path                = "Longest path along flow direction (m).",
  nearest_downstream_stream_pixel = "Nearest downstream stream pixel (index, dimensionless).",
  seg_down_mean_grad          = "Segment downstream mean gradient (m/m).",
  seg_up_mean_grad            = "Segment upstream mean gradient (m/m).",
  cell_upstream_grad          = "Cell upstream gradient (m/m).",
  cell_stream_course_curv     = "Cell stream course curvature (dimensionless).",
  seg_down_elev_diff          = "Segment downstream elevation difference (m).",
  seg_up_elev_diff            = "Segment upstream elevation difference (m).",
  cell_upstream_elev_diff     = "Cell upstream elevation difference (m).",
  cell_downstream_elev_diff   = "Cell downstream elevation difference (m).",
  seg_down_dist               = "Segment downstream distance (m).",
  seg_up_dist                 = "Segment upstream distance (m).",
  cell_upstream_dist          = "Cell upstream distance (m).",
  stream_strahler             = "Strahler’s stream order (dimensionless).",
  stream_shreve               = "Shreve’s stream magnitude (dimensionless).",
  stream_horton               = "Horton’s stream order (dimensionless).",
  stream_hack                 = "Hack’s stream order (dimensionless).",
  topo_dim_streams            = "Topological dimension of streams (dimensionless).",
  length                      = "Length of the stream reach (m).",
  stright                     = "Straight length of the stream reach (m).",
  sinusoid                    = "Sinusoid (ratio, dimensionless).",
  cum_length                  = "Accumulated length (m).",
  out_dist                    = "Distance to outlet (m).",
  source_elev                 = "Source elevation (m).",
  outlet_elev                 = "Outlet elevation (m).",
  elev_drop                   = "Elevation drop (m).",
  out_drop                    = "Outlet drop (m).",
  gradient                    = "Gradient (m/m, slope).",
  spi                         = "Stream Power Index (dimensionless).",
  sti                         = "Sediment Transport Index (dimensionless).",
  cti                         = "Compound Topographic Index (dimensionless)."
)

# ==== Land cover (ESA CCI / Copernicus) ====
Landcover_choices <- c(
  "Cropland, rainfed (c10)"                           = "c10",
  "Cropland, irrigated/post-flooding (c20)"           = "c20",
  "Cropland/natural vegetation (c30)"                 = "c30",
  "Natural vegetation/cropland (c40)"                 = "c40",
  "Tree cover, broadleaved, evergreen (c50)"          = "c50",
  "Tree cover, broadleaved, deciduous (c60)"          = "c60",
  "Tree cover, needleleaved, evergreen (c70)"         = "c70",
  "Tree cover, needleleaved, deciduous (c80)"         = "c80",
  "Tree cover, mixed leaf type (c90)"                 = "c90",
  "Tree and shrub (c100)"                             = "c100",
  "Herbaceous/tree and shrub (c110)"                  = "c110",
  "Shrubland (c120)"                                  = "c120",
  "Grassland (c130)"                                  = "c130",
  "Lichens, mosses (c140)"                            = "c140",
  "Sparse vegetation (c150)"                          = "c150",
  "Tree cover, flooded, fresh/brackish water (c160)"  = "c160",
  "Tree cover, flooded, saline water (c170)"          = "c170",
  "Shrub or herbaceous (c180)"                        = "c180",
  "Urban areas (c190)"                                = "c190",
  "Bare areas (c200)"                                 = "c200",
  "Water bodies (c210)"                               = "c210",
  "Snow and ice (c220)"                               = "c220"
)

Landcover_desc <- c(
  c10  = "Cropland, rainfed – areas of cultivated crops dependent on rainfall.",
  c20  = "Cropland, irrigated/post-flooding – cultivated areas with irrigation or flooding practices.",
  c30  = "Cropland/natural vegetation mosaic – mixed areas dominated by cropland with natural vegetation patches.",
  c40  = "Natural vegetation/cropland mosaic – mixed areas dominated by natural vegetation with cropland patches.",
  c50  = "Tree cover, broadleaved, evergreen – closed to open forests with evergreen broadleaf trees.",
  c60  = "Tree cover, broadleaved, deciduous – forests with predominantly deciduous broadleaf trees.",
  c70  = "Tree cover, needleleaved, evergreen – coniferous forests with evergreen needleleaf trees.",
  c80  = "Tree cover, needleleaved, deciduous – coniferous forests with deciduous needleleaf trees.",
  c90  = "Tree cover, mixed leaf type – forests with mixed broadleaf and needleleaf species.",
  c100 = "Tree and shrub – woody vegetation combining trees and shrubs.",
  c110 = "Herbaceous/tree and shrub – mixed vegetation of herbs with trees and shrubs.",
  c120 = "Shrubland – areas dominated by shrubs with sparse or no tree cover.",
  c130 = "Grassland – areas dominated by grasses and herbaceous vegetation.",
  c140 = "Lichens, mosses – tundra or ground cover dominated by lichens and mosses.",
  c150 = "Sparse vegetation – areas with very low vegetation cover (desert, semi-desert).",
  c160 = "Tree cover, flooded, fresh/brackish water – forests seasonally or permanently flooded with fresh/brackish water.",
  c170 = "Tree cover, flooded, saline water – forests seasonally or permanently flooded with saline water.",
  c180 = "Shrub or herbaceous cover – vegetation dominated by shrubs or herbaceous plants.",
  c190 = "Urban areas – built-up and artificial surfaces.",
  c200 = "Bare areas – lands with little or no vegetation (rock, sand, desert).",
  c210 = "Water bodies – permanent or seasonal inland water surfaces.",
  c220 = "Snow and ice – permanent snow fields and glaciers."
)

# ==== Combine groups into one list ====
Variable_groups <- list(
  Climate     = list(choices = Climate_choices,     desc = Climate_desc),
  Soil        = list(choices = Soil_choices,        desc = Soil_desc),
  Topography  = list(choices = Topography_choices,  desc = Topography_desc),
  Landcover   = list(choices = Landcover_choices,   desc = Landcover_desc)
)
